using WinTweaker.Models;
using WinTweaker.Services;

namespace WinTweaker.Data;

/// <summary>
/// All tweaks, ported 1:1 from the Python version. Commands are cmd.exe strings.
/// EN/RU names &amp; descriptions share the same commands.
/// </summary>
public static class TweakData
{
    public static readonly string[] Order =
        { "performance", "gaming", "explorer", "power", "telemetry", "privacy",
          "security", "ads", "network", "cleanup" };

    /// <summary>Builds the section -> tweaks map for a language, applying saved states.</summary>
    public static Dictionary<string, List<Tweak>> Build(string lang, Settings settings)
    {
        bool ru = lang != "en";
        var data = new Dictionary<string, List<Tweak>>();

        Tweak T(string id, string ruN, string ruD, string enN, string enD, string en, string dis) => new()
        {
            Id = id,
            Name = ru ? ruN : enN,
            Desc = ru ? ruD : enD,
            Enable = en,
            Disable = dis,
            IsEnabled = settings.GetTweak(id),
        };

        data["performance"] = new()
        {
            T("max_power", "Максимальная производительность питания", "Переключает схему питания на «Максимальная производительность»",
              "Max Performance Power Plan", "Switches to Maximum Performance power plan",
              @"powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c",
              @"powercfg /setactive 381b4222-f694-41f0-9685-ff5bb260df2e"),
            T("superfetch", "Отключить SysMain (Superfetch)", "Освобождает ОЗУ — полезно если меньше 8 ГБ",
              "Disable SysMain", "Frees RAM — useful with 8GB or less",
              @"sc stop SysMain & sc config SysMain start=disabled",
              @"sc config SysMain start=auto & sc start SysMain"),
            T("search_idx", "Отключить индексирование поиска", "Снижает нагрузку на диск",
              "Disable Search Indexing", "Reduces disk load",
              @"sc stop WSearch & sc config WSearch start=disabled",
              @"sc config WSearch start=delayed-auto & sc start WSearch"),
            T("visual_fx", "Отключить визуальные эффекты", "Убирает анимации и тени — интерфейс отзывчивее",
              "Disable Visual Effects", "Removes animations and shadows",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects"" /v VisualFXSetting /t REG_DWORD /d 2 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects"" /v VisualFXSetting /t REG_DWORD /d 0 /f"),
            T("game_mode", "Включить Game Mode", "Оптимизирует ресурсы CPU/GPU под игры",
              "Enable Game Mode", "Prioritizes CPU/GPU for games",
              @"reg add ""HKCU\Software\Microsoft\GameBar"" /v AutoGameModeEnabled /t REG_DWORD /d 1 /f",
              @"reg add ""HKCU\Software\Microsoft\GameBar"" /v AutoGameModeEnabled /t REG_DWORD /d 0 /f"),
            T("fast_startup", "Быстрый запуск Windows", "Ускоряет загрузку системы через гибернацию ядра",
              "Fast Startup", "Speeds up boot via kernel hibernation",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Power"" /v HiberbootEnabled /t REG_DWORD /d 1 /f",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Power"" /v HiberbootEnabled /t REG_DWORD /d 0 /f"),
            T("timer_res", "Высокое разрешение таймера", "Уменьшает задержки — полезно для игр и аудио",
              "High Timer Resolution", "Reduces latency for gaming/audio",
              @"reg add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile"" /v SystemResponsiveness /t REG_DWORD /d 0 /f",
              @"reg add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile"" /v SystemResponsiveness /t REG_DWORD /d 20 /f"),
            T("hags", "Аппаратное ускорение GPU (HAGS)", "Снижает задержку GPU в DirectX 12 (Win10 2004+)",
              "GPU Hardware Scheduling", "Reduces GPU latency in DX12 (Win10 2004+)",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers"" /v HwSchMode /t REG_DWORD /d 2 /f",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers"" /v HwSchMode /t REG_DWORD /d 1 /f"),
            T("cpu_prio", "Приоритет CPU для активных программ", "ОС отдаёт больше ресурсов активному окну",
              "CPU Priority for Active Apps", "OS gives more CPU to foreground window",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\PriorityControl"" /v Win32PrioritySeparation /t REG_DWORD /d 38 /f",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\PriorityControl"" /v Win32PrioritySeparation /t REG_DWORD /d 2 /f"),
            T("meltdown", "Отключить Meltdown/Spectre патч ⚠", "Снижает безопасность, но даёт +10% CPU — только домашние ПК",
              "Disable Meltdown/Spectre Patch ⚠", "Reduces security but gains ~10% CPU perf",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management"" /v FeatureSettingsOverride /t REG_DWORD /d 3 /f & reg add ""HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management"" /v FeatureSettingsOverrideMask /t REG_DWORD /d 3 /f",
              @"reg delete ""HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management"" /v FeatureSettingsOverride /f"),
            T("hibernate", "Отключить гибернацию", "Удаляет hiberfil.sys — освобождает место",
              "Disable Hibernation", "Removes hiberfil.sys — frees disk space",
              @"powercfg /hibernate off", @"powercfg /hibernate on"),
            T("transparency", "Отключить эффекты прозрачности", "Убирает полупрозрачность окон и поверхностей — чище и быстрее",
              "Disable Transparency Effects", "Removes window transparency — cleaner & faster",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"" /v EnableTransparency /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"" /v EnableTransparency /t REG_DWORD /d 1 /f"),
            T("dark_mode_p", "Включить тёмную тему системы", "Тёмный режим для всех окон и системных элементов Windows",
              "Enable System Dark Theme", "Dark mode for all windows and system elements",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"" /v AppsUseLightTheme /t REG_DWORD /d 0 /f & reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"" /v SystemUsesLightTheme /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"" /v AppsUseLightTheme /t REG_DWORD /d 1 /f & reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"" /v SystemUsesLightTheme /t REG_DWORD /d 1 /f"),
            T("hide_search", "Скрыть поиск на панели задач", "Убирает поле/значок поиска с панели задач — чище интерфейс",
              "Hide Taskbar Search", "Removes the search box/icon from the taskbar",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Search"" /v SearchboxTaskbarMode /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Search"" /v SearchboxTaskbarMode /t REG_DWORD /d 2 /f"),
            T("hide_widgets", "Скрыть виджеты на панели задач", "Убирает кнопку виджетов (погода/новости) с панели задач",
              "Hide Taskbar Widgets", "Removes the Widgets (weather/news) button",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v TaskbarDa /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v TaskbarDa /t REG_DWORD /d 1 /f"),
            T("wu_disable", "Отключить автообновления Windows ⚠", "Останавливает службу обновлений и убирает авто-перезагрузку",
              "Disable Windows Auto-Update ⚠", "Stops the update service and prevents auto-reboot",
              @"sc stop wuauserv & sc config wuauserv start=disabled & reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU"" /v NoAutoRebootWithLoggedOnUsers /t REG_DWORD /d 1 /f",
              @"sc config wuauserv start=auto & sc start wuauserv & reg delete ""HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU"" /v NoAutoRebootWithLoggedOnUsers /f"),
            T("menu_delay", "Ускорить отображение меню", "Убирает задержку появления меню — интерфейс реагирует мгновенно",
              "Faster Menu Delay", "Removes the menu show delay — snappier UI",
              @"reg add ""HKCU\Control Panel\Desktop"" /v MenuShowDelay /t REG_SZ /d 0 /f",
              @"reg add ""HKCU\Control Panel\Desktop"" /v MenuShowDelay /t REG_SZ /d 400 /f"),
            T("startup_delay_off", "Убрать задержку запуска программ", "Программы автозагрузки стартуют сразу, без искусственной паузы",
              "Remove App Startup Delay", "Startup apps launch immediately, no artificial delay",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Serialize"" /v StartupDelayInMSec /t REG_DWORD /d 0 /f",
              @"reg delete ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Serialize"" /v StartupDelayInMSec /f"),
            T("ndu_off", "Отключить Ndu (экономит ОЗУ)", "Выключает службу мониторинга сетевого трафика — освобождает память",
              "Disable Ndu (frees RAM)", "Disables the network data usage driver — frees memory",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Services\Ndu"" /v Start /t REG_DWORD /d 4 /f",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Services\Ndu"" /v Start /t REG_DWORD /d 2 /f"),
            T("power_throttle_off", "Отключить Power Throttling", "ОС перестаёт занижать частоту фоновых процессов — стабильнее производительность",
              "Disable Power Throttling", "OS stops throttling background processes — steadier performance",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling"" /v PowerThrottlingOff /t REG_DWORD /d 1 /f",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling"" /v PowerThrottlingOff /t REG_DWORD /d 0 /f"),
        };

        data["gaming"] = new()
        {
            T("gamedvr_off", "Отключить Game DVR (фоновая запись)", "Выключает фоновую запись игр — меньше нагрузка и выше FPS",
              "Disable Game DVR", "Turns off background game recording — less overhead, higher FPS",
              @"reg add ""HKCU\System\GameConfigStore"" /v GameDVR_Enabled /t REG_DWORD /d 0 /f & reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\GameDVR"" /v AllowGameDVR /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\System\GameConfigStore"" /v GameDVR_Enabled /t REG_DWORD /d 1 /f & reg delete ""HKLM\SOFTWARE\Policies\Microsoft\Windows\GameDVR"" /v AllowGameDVR /f"),
            T("xbox_gamebar_off", "Отключить Xbox Game Bar", "Выключает игровую панель Xbox и её захват — меньше фоновых процессов",
              "Disable Xbox Game Bar", "Turns off the Xbox Game Bar and its capture — fewer background processes",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\GameDVR"" /v AppCaptureEnabled /t REG_DWORD /d 0 /f & reg add ""HKCU\System\GameConfigStore"" /v GameDVR_Enabled /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\GameDVR"" /v AppCaptureEnabled /t REG_DWORD /d 1 /f & reg add ""HKCU\System\GameConfigStore"" /v GameDVR_Enabled /t REG_DWORD /d 1 /f"),
            T("mouse_accel_off", "Отключить акселерацию мыши", "Прямое соответствие движения мыши — точнее прицел в играх",
              "Disable Mouse Acceleration", "1:1 mouse movement — more precise aim in games",
              @"reg add ""HKCU\Control Panel\Mouse"" /v MouseSpeed /t REG_SZ /d 0 /f & reg add ""HKCU\Control Panel\Mouse"" /v MouseThreshold1 /t REG_SZ /d 0 /f & reg add ""HKCU\Control Panel\Mouse"" /v MouseThreshold2 /t REG_SZ /d 0 /f",
              @"reg add ""HKCU\Control Panel\Mouse"" /v MouseSpeed /t REG_SZ /d 1 /f & reg add ""HKCU\Control Panel\Mouse"" /v MouseThreshold1 /t REG_SZ /d 6 /f & reg add ""HKCU\Control Panel\Mouse"" /v MouseThreshold2 /t REG_SZ /d 10 /f"),
            T("fso_off", "Отключить полноэкранную оптимизацию", "Игры запускаются в эксклюзивном полноэкранном режиме — меньше задержка",
              "Disable Fullscreen Optimizations", "Games run in exclusive fullscreen — lower latency",
              @"reg add ""HKCU\System\GameConfigStore"" /v GameDVR_FSEBehaviorMode /t REG_DWORD /d 2 /f & reg add ""HKCU\System\GameConfigStore"" /v GameDVR_DXGIHonorFSEWindowsCompatible /t REG_DWORD /d 1 /f",
              @"reg add ""HKCU\System\GameConfigStore"" /v GameDVR_FSEBehaviorMode /t REG_DWORD /d 0 /f & reg add ""HKCU\System\GameConfigStore"" /v GameDVR_DXGIHonorFSEWindowsCompatible /t REG_DWORD /d 0 /f"),
            T("net_throttle_off", "Отключить сетевой троттлинг", "Снимает ограничение сетевого потока — полезно для игр и стриминга",
              "Disable Network Throttling", "Removes the network throttling cap — good for gaming and streaming",
              @"reg add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile"" /v NetworkThrottlingIndex /t REG_DWORD /d 0xffffffff /f",
              @"reg add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile"" /v NetworkThrottlingIndex /t REG_DWORD /d 10 /f"),
            T("games_priority", "Высокий приоритет для игр (MMCSS)", "Планировщик отдаёт играм больше CPU и GPU через профиль мультимедиа",
              "High Priority for Games (MMCSS)", "The scheduler gives games more CPU and GPU via the multimedia profile",
              @"reg add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games"" /v Priority /t REG_DWORD /d 6 /f & reg add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games"" /v ""Scheduling Category"" /t REG_SZ /d High /f & reg add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games"" /v ""GPU Priority"" /t REG_DWORD /d 8 /f",
              @"reg add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games"" /v Priority /t REG_DWORD /d 2 /f & reg add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games"" /v ""Scheduling Category"" /t REG_SZ /d Medium /f & reg add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games"" /v ""GPU Priority"" /t REG_DWORD /d 8 /f"),
        };

        data["explorer"] = new()
        {
            T("launch_thispc", "Открывать Проводник в «Этот компьютер»", "Проводник открывается на «Этот компьютер», а не на «Быстрый доступ»",
              "Open Explorer to This PC", "Explorer opens to This PC instead of Quick Access",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v LaunchTo /t REG_DWORD /d 1 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v LaunchTo /t REG_DWORD /d 2 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe"),
            T("taskbar_left", "Панель задач слева (Win11)", "Выравнивает значки панели задач по левому краю, как в Windows 10",
              "Align Taskbar Left (Win11)", "Aligns taskbar icons to the left, like Windows 10",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v TaskbarAl /t REG_DWORD /d 0 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v TaskbarAl /t REG_DWORD /d 1 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe"),
            T("compact_mode", "Компактный вид Проводника (Win11)", "Уменьшает отступы между элементами в Проводнике",
              "Compact View (Win11)", "Reduces spacing between items in Explorer",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v UseCompactMode /t REG_DWORD /d 1 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v UseCompactMode /t REG_DWORD /d 0 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe"),
            T("show_seconds", "Показывать секунды в часах", "Часы на панели задач отображают секунды",
              "Show Seconds in Clock", "The taskbar clock shows seconds",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v ShowSecondsInSystemClock /t REG_DWORD /d 1 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v ShowSecondsInSystemClock /t REG_DWORD /d 0 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe"),
            T("end_task", "«Завершить задачу» в панели задач (Win11)", "Добавляет пункт «Завершить задачу» в меню правого клика по приложению на панели задач",
              "End Task on taskbar (Win11)", "Adds 'End Task' to the taskbar app right-click menu",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarDeveloperSettings"" /v TaskbarEndTask /t REG_DWORD /d 1 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarDeveloperSettings"" /v TaskbarEndTask /t REG_DWORD /d 0 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe"),
            T("aero_shake_off", "Отключить Aero Shake", "Тряска окна больше не сворачивает все остальные окна",
              "Disable Aero Shake", "Shaking a window no longer minimizes the others",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v DisallowShaking /t REG_DWORD /d 1 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v DisallowShaking /t REG_DWORD /d 0 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe"),
            T("no_recent_files", "Скрыть недавние файлы в Быстром доступе", "Проводник не показывает список недавно открытых файлов",
              "Hide Recent Files in Quick Access", "Explorer won't show recently opened files",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer"" /v ShowRecent /t REG_DWORD /d 0 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer"" /v ShowRecent /t REG_DWORD /d 1 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe"),
            T("no_frequent_folders", "Скрыть частые папки в Быстром доступе", "Проводник не показывает список часто используемых папок",
              "Hide Frequent Folders in Quick Access", "Explorer won't show frequently used folders",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer"" /v ShowFrequent /t REG_DWORD /d 0 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer"" /v ShowFrequent /t REG_DWORD /d 1 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe"),
            T("verbose_status", "Подробные сообщения загрузки/выключения", "Windows показывает детальные статусы при входе и выключении",
              "Verbose Boot/Shutdown Messages", "Windows shows detailed status during sign-in and shutdown",
              @"reg add ""HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"" /v VerboseStatus /t REG_DWORD /d 1 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe",
              @"reg add ""HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"" /v VerboseStatus /t REG_DWORD /d 0 /f & taskkill /f /im explorer.exe >nul 2>&1 & start explorer.exe"),
        };

        data["power"] = new()
        {
            T("ultimate_power", "Разблокировать «Максимальную производительность»", "Создаёт скрытую схему питания Ultimate Performance",
              "Unlock Ultimate Performance Plan", "Creates the hidden Ultimate Performance power scheme",
              @"powercfg -duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61", @"echo N/A"),
            T("usb_suspend_off", "Отключить приостановку USB", "USB-устройства не уходят в энергосбережение — стабильнее периферия",
              "Disable USB Selective Suspend", "USB devices won't power-save — steadier peripherals",
              @"powercfg /setacvalueindex SCHEME_CURRENT 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 0 & powercfg /setactive SCHEME_CURRENT",
              @"powercfg /setacvalueindex SCHEME_CURRENT 2a737441-1930-4402-8d77-b2bebba308a3 48e6b7a6-50f5-4782-a5d4-53bb8f07e226 1 & powercfg /setactive SCHEME_CURRENT"),
            T("monitor_never_off", "Не отключать экран (от сети)", "Дисплей не гаснет при работе от сети",
              "Never Turn Off Display (AC)", "The display won't sleep while on AC power",
              @"powercfg /change monitor-timeout-ac 0", @"powercfg /change monitor-timeout-ac 10"),
            T("sleep_never", "Не уходить в спящий режим (от сети)", "ПК не засыпает при работе от сети",
              "Never Sleep (AC)", "The PC won't sleep while on AC power",
              @"powercfg /change standby-timeout-ac 0", @"powercfg /change standby-timeout-ac 30"),
            T("disk_never_off", "Не отключать жёсткий диск (от сети)", "Жёсткий диск не паркуется при простое — без задержек доступа",
              "Never Turn Off Hard Disk (AC)", "The hard disk won't spin down on idle — no access lag",
              @"powercfg /change disk-timeout-ac 0", @"powercfg /change disk-timeout-ac 20"),
        };

        data["telemetry"] = new()
        {
            T("tel_main", "Отключить телеметрию и сбор данных", "Гасит ВСЕ галочки приватности: телеметрию, рекламный ID, рекомендации, голос, рукописный ввод, диагностику, историю активности",
              "Disable Telemetry & Data Collection", "Turns OFF all privacy toggles: telemetry, ad ID, suggestions, speech, inking, diagnostics, activity history",
              @"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection"" /v AllowTelemetry /t REG_DWORD /d 0 /f & sc stop DiagTrack & sc config DiagTrack start=disabled & reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo"" /v Enabled /t REG_DWORD /d 0 /f & reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Privacy"" /v TailoredExperiencesWithDiagnosticDataEnabled /t REG_DWORD /d 0 /f & reg add ""HKCU\Software\Microsoft\Speech_OneCore\Settings\OnlineSpeechPrivacy"" /v HasAccepted /t REG_DWORD /d 0 /f & reg add ""HKCU\Software\Microsoft\InputPersonalization"" /v RestrictImplicitTextCollection /t REG_DWORD /d 1 /f & reg add ""HKCU\Software\Microsoft\InputPersonalization"" /v RestrictImplicitInkCollection /t REG_DWORD /d 1 /f & reg add ""HKCU\Software\Microsoft\Personalization\Settings"" /v AcceptedPrivacyPolicy /t REG_DWORD /d 0 /f & reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\System"" /v EnableActivityFeed /t REG_DWORD /d 0 /f & reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\System"" /v PublishUserActivities /t REG_DWORD /d 0 /f & reg add ""HKCU\Software\Microsoft\Siuf\Rules"" /v NumberOfSIUFInPeriod /t REG_DWORD /d 0 /f",
              @"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection"" /v AllowTelemetry /t REG_DWORD /d 1 /f & sc config DiagTrack start=auto & reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo"" /v Enabled /t REG_DWORD /d 1 /f & reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Privacy"" /v TailoredExperiencesWithDiagnosticDataEnabled /t REG_DWORD /d 1 /f & reg add ""HKCU\Software\Microsoft\Speech_OneCore\Settings\OnlineSpeechPrivacy"" /v HasAccepted /t REG_DWORD /d 1 /f & reg add ""HKCU\Software\Microsoft\InputPersonalization"" /v RestrictImplicitTextCollection /t REG_DWORD /d 0 /f & reg add ""HKCU\Software\Microsoft\InputPersonalization"" /v RestrictImplicitInkCollection /t REG_DWORD /d 0 /f & reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\System"" /v EnableActivityFeed /t REG_DWORD /d 1 /f"),
            T("activity", "Отключить историю активности", "Microsoft не хранит историю ваших действий",
              "Disable Activity History", "Won't store activity history",
              @"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\System"" /v EnableActivityFeed /t REG_DWORD /d 0 /f",
              @"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\System"" /v EnableActivityFeed /t REG_DWORD /d 1 /f"),
            T("diagtrack", "Отключить DiagTrack (Connected UE)", "Останавливает главную службу слежки",
              "Disable DiagTrack", "Stops main tracking service",
              @"sc stop DiagTrack & sc config DiagTrack start=disabled",
              @"sc config DiagTrack start=auto & sc start DiagTrack"),
            T("compat_tel", "Отключить CompatTelRunner", "Останавливает задачи сбора данных совместимости",
              "Disable CompatTelRunner", "Stops compat data collection",
              @"schtasks /Change /TN ""Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser"" /Disable",
              @"schtasks /Change /TN ""Microsoft\Windows\Application Experience\Microsoft Compatibility Appraiser"" /Enable"),
            T("location", "Отключить геолокацию", "Запрещает приложениям доступ к местоположению",
              "Disable Location", "No app location access",
              @"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors"" /v DisableLocation /t REG_DWORD /d 1 /f",
              @"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\LocationAndSensors"" /v DisableLocation /t REG_DWORD /d 0 /f"),
            T("feedback", "Отключить запросы обратной связи", "Убирает опросы Microsoft",
              "Disable Feedback Requests", "Removes Microsoft survey popups",
              @"reg add ""HKCU\Software\Microsoft\Siuf\Rules"" /v NumberOfSIUFInPeriod /t REG_DWORD /d 0 /f",
              @"reg delete ""HKCU\Software\Microsoft\Siuf\Rules"" /v NumberOfSIUFInPeriod /f"),
            T("adv_id", "Отключить рекламный ID", "Запрещает использовать рекламный идентификатор",
              "Disable Advertising ID", "No advertising identifier",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo"" /v Enabled /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo"" /v Enabled /t REG_DWORD /d 1 /f"),
            T("cortana", "Отключить Cortana", "Деактивирует голосового ассистента",
              "Disable Cortana", "Disables Cortana voice assistant",
              @"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search"" /v AllowCortana /t REG_DWORD /d 0 /f",
              @"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search"" /v AllowCortana /t REG_DWORD /d 1 /f"),
            T("wer", "Отключить отчёты об ошибках", "Прекращает отправку crash-отчётов в Microsoft",
              "Disable Error Reporting", "Stops crash reports to Microsoft",
              @"sc stop WerSvc & sc config WerSvc start=disabled & reg add ""HKLM\SOFTWARE\Microsoft\Windows\Windows Error Reporting"" /v Disabled /t REG_DWORD /d 1 /f",
              @"sc config WerSvc start=demand"),
            T("speech_off", "Отключить онлайн-распознавание речи", "Голос не отправляется в облако Microsoft для распознавания",
              "Disable Online Speech Recognition", "Voice won't be sent to Microsoft's cloud for recognition",
              @"reg add ""HKCU\Software\Microsoft\Speech_OneCore\Settings\OnlineSpeechPrivacy"" /v HasAccepted /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Speech_OneCore\Settings\OnlineSpeechPrivacy"" /v HasAccepted /t REG_DWORD /d 1 /f"),
            T("find_device_off", "Отключить «Поиск устройства»", "Windows не отслеживает местоположение устройства",
              "Disable Find My Device", "Windows won't track your device location",
              @"reg add ""HKLM\SOFTWARE\Microsoft\Settings\FindMyDevice"" /v LocationSyncEnabled /t REG_DWORD /d 0 /f",
              @"reg add ""HKLM\SOFTWARE\Microsoft\Settings\FindMyDevice"" /v LocationSyncEnabled /t REG_DWORD /d 1 /f"),
            T("cloud_content_off", "Отключить облачный контент", "Прекращает загрузку рекомендованного облачного контента и предложений",
              "Disable Cloud-Optimized Content", "Stops downloading cloud-optimized content and suggestions",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v ContentDeliveryAllowed /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v ContentDeliveryAllowed /t REG_DWORD /d 1 /f"),
        };

        data["security"] = new()
        {
            T("autorun_off", "Отключить автозапуск носителей", "Блокирует автоматический запуск программ с USB/CD — защита от вредоносов",
              "Disable AutoRun/AutoPlay", "Blocks auto-launching from USB/CD — protects against malware",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer"" /v NoDriveTypeAutoRun /t REG_DWORD /d 255 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer"" /v NoDriveTypeAutoRun /t REG_DWORD /d 145 /f"),
            T("smbv1_off", "Отключить SMBv1", "Выключает устаревший небезопасный протокол SMBv1 (уязвимость WannaCry)",
              "Disable SMBv1", "Turns off the obsolete, insecure SMBv1 protocol (WannaCry vector)",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters"" /v SMB1 /t REG_DWORD /d 0 /f",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters"" /v SMB1 /t REG_DWORD /d 1 /f"),
            T("llmnr_off", "Отключить LLMNR", "Закрывает протокол LLMNR — снижает риск перехвата учётных данных в сети",
              "Disable LLMNR", "Closes the LLMNR protocol — reduces credential-theft risk on the network",
              @"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient"" /v EnableMulticast /t REG_DWORD /d 0 /f",
              @"reg delete ""HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient"" /v EnableMulticast /f"),
            T("remote_assist_off", "Отключить удалённый помощник", "Запрещает удалённые подключения через Remote Assistance",
              "Disable Remote Assistance", "Blocks inbound Remote Assistance connections",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\Remote Assistance"" /v fAllowToGetHelp /t REG_DWORD /d 0 /f",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Control\Remote Assistance"" /v fAllowToGetHelp /t REG_DWORD /d 1 /f"),
            T("uac_off", "Отключить UAC (контроль учётных записей) ⚠", "Убирает запросы подтверждения, но заметно снижает безопасность системы",
              "Disable UAC ⚠", "Removes confirmation prompts but notably lowers system security",
              @"reg add ""HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"" /v EnableLUA /t REG_DWORD /d 0 /f",
              @"reg add ""HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System"" /v EnableLUA /t REG_DWORD /d 1 /f"),
            T("smartscreen_off", "Отключить SmartScreen ⚠", "Отключает фильтр репутации файлов и приложений — снижает защиту",
              "Disable SmartScreen ⚠", "Turns off the file/app reputation filter — reduces protection",
              @"reg add ""HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer"" /v SmartScreenEnabled /t REG_SZ /d Off /f & reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\System"" /v EnableSmartScreen /t REG_DWORD /d 0 /f",
              @"reg add ""HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer"" /v SmartScreenEnabled /t REG_SZ /d Warn /f & reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\System"" /v EnableSmartScreen /t REG_DWORD /d 1 /f"),
        };

        data["ads"] = new()
        {
            T("start_ads", "Убрать рекламу в меню Пуск", "Отключает рекламные плитки и предложения",
              "Remove Start Menu Ads", "Disables ad tiles",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SystemPaneSuggestionsEnabled /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SystemPaneSuggestionsEnabled /t REG_DWORD /d 1 /f"),
            T("lock_ads", "Убрать рекламу на экране блокировки", "Отключает Windows Spotlight и советы",
              "Remove Lock Screen Ads", "Disables Windows Spotlight",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v RotatingLockScreenEnabled /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v RotatingLockScreenEnabled /t REG_DWORD /d 1 /f"),
            T("tips", "Отключить советы Windows", "Убирает всплывающие подсказки",
              "Disable Tips", "Removes popups",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SoftLandingEnabled /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SoftLandingEnabled /t REG_DWORD /d 1 /f"),
            T("auto_inst", "Отключить автоустановку приложений", "Запрещает тихую установку bloatware",
              "Disable Silent App Install", "Prevents silent bloatware",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SilentInstalledAppsEnabled /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SilentInstalledAppsEnabled /t REG_DWORD /d 1 /f"),
            T("bing", "Убрать Bing из поиска", "Поиск в Пуске не лезет в интернет",
              "Remove Bing from Search", "Start search won't use internet",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Search"" /v BingSearchEnabled /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Search"" /v BingSearchEnabled /t REG_DWORD /d 1 /f"),
            T("edge_ads", "Отключить рекламу в Edge", "Убирает рекламные плитки на новой вкладке Edge",
              "Disable Edge Ads", "Removes ad tiles in Edge",
              @"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Edge"" /v NewTabPageContentEnabled /t REG_DWORD /d 0 /f",
              @"reg delete ""HKLM\SOFTWARE\Policies\Microsoft\Edge"" /v NewTabPageContentEnabled /f"),
            T("disable_copilot", "Отключить и убрать Copilot (ИИ)", "Выключает Windows Copilot и убирает кнопку с панели задач",
              "Disable & remove Copilot (AI)", "Turns off Windows Copilot and removes its taskbar button",
              @"reg add ""HKCU\Software\Policies\Microsoft\Windows\WindowsCopilot"" /v TurnOffWindowsCopilot /t REG_DWORD /d 1 /f & reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsCopilot"" /v TurnOffWindowsCopilot /t REG_DWORD /d 1 /f & reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v ShowCopilotButton /t REG_DWORD /d 0 /f & powershell -NoProfile -Command ""Get-AppxPackage *Copilot* | Remove-AppxPackage -EA SilentlyContinue""",
              @"reg add ""HKCU\Software\Policies\Microsoft\Windows\WindowsCopilot"" /v TurnOffWindowsCopilot /t REG_DWORD /d 0 /f & reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v ShowCopilotButton /t REG_DWORD /d 1 /f"),
            T("disable_recall", "Отключить Windows Recall (ИИ) ⚠", "Выключает функцию Recall, делающую снимки экрана для ИИ",
              "Disable Windows Recall (AI) ⚠", "Turns off Recall, which snapshots your screen for AI",
              @"reg add ""HKCU\Software\Policies\Microsoft\Windows\WindowsAI"" /v DisableAIDataAnalysis /t REG_DWORD /d 1 /f & reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsAI"" /v DisableAIDataAnalysis /t REG_DWORD /d 1 /f & dism /online /disable-feature /featurename:Recall /norestart",
              @"reg add ""HKCU\Software\Policies\Microsoft\Windows\WindowsAI"" /v DisableAIDataAnalysis /t REG_DWORD /d 0 /f & reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsAI"" /v DisableAIDataAnalysis /t REG_DWORD /d 0 /f"),
            T("remove_onedrive", "Удалить OneDrive", "Полностью удаляет OneDrive из системы",
              "Remove OneDrive", "Fully uninstalls OneDrive from the system",
              @"taskkill /f /im OneDrive.exe 2>nul & ""%SystemRoot%\System32\OneDriveSetup.exe"" /uninstall & ""%SystemRoot%\SysWOW64\OneDriveSetup.exe"" /uninstall",
              @"echo N/A"),
            T("remove_edge", "Удалить Microsoft Edge ⚠", "Пытается удалить Edge официальным деинсталлятором (может не сработать в некоторых регионах)",
              "Remove Microsoft Edge ⚠", "Tries to uninstall Edge via its official uninstaller (may be blocked in some regions)",
              @"powershell -NoProfile -Command ""$s=(Get-ChildItem 'C:\Program Files (x86)\Microsoft\Edge\Application' -Filter setup.exe -Recurse -EA SilentlyContinue | Select-Object -First 1).FullName; if($s){ Start-Process $s -ArgumentList '--uninstall --system-level --force-uninstall' -Wait }""",
              @"echo N/A"),
            T("settings_suggest_off", "Убрать рекомендации в Параметрах", "Отключает рекламные подсказки и предложения внутри приложения «Параметры»",
              "Remove Settings Suggestions", "Disables promo tips and suggestions inside the Settings app",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SubscribedContent-338393Enabled /t REG_DWORD /d 0 /f & reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SubscribedContent-353694Enabled /t REG_DWORD /d 0 /f & reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SubscribedContent-353696Enabled /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SubscribedContent-338393Enabled /t REG_DWORD /d 1 /f & reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SubscribedContent-353694Enabled /t REG_DWORD /d 1 /f & reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SubscribedContent-353696Enabled /t REG_DWORD /d 1 /f"),
            T("finish_setup_off", "Убрать «Завершить настройку устройства»", "Отключает навязчивый экран дополнительной настройки после входа",
              "Remove 'Finish Setting Up' Nags", "Disables the post-login 'finish setting up your device' screen",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\UserProfileEngagement"" /v ScoobeSystemSettingEnabled /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\UserProfileEngagement"" /v ScoobeSystemSettingEnabled /t REG_DWORD /d 1 /f"),
            T("welcome_exp_off", "Убрать экран приветствия после обновлений", "Отключает страницу «Что нового» после установки обновлений",
              "Remove Post-Update Welcome Screen", "Disables the 'What's new' page shown after updates",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SubscribedContent-310093Enabled /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SubscribedContent-310093Enabled /t REG_DWORD /d 1 /f"),
            T("explorer_ads_off", "Убрать рекламу в Проводнике", "Отключает рекламные уведомления провайдеров синхронизации (OneDrive и т.п.)",
              "Remove Explorer Ads", "Disables sync provider promo notifications (OneDrive etc.)",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v ShowSyncProviderNotifications /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v ShowSyncProviderNotifications /t REG_DWORD /d 1 /f"),
        };

        data["cleanup"] = new()
        {
            T("temp", "Очистить временные файлы", "Удаляет файлы из %TEMP% и Windows\\Temp",
              "Clear Temp Files", "Deletes from %TEMP% and Windows Temp",
              @"cmd /c ""del /q /f /s %TEMP%\* 2>nul & del /q /f /s C:\Windows\Temp\* 2>nul""", @"echo N/A"),
            T("prefetch", "Очистить Prefetch", "Удаляет кэш предзагрузки",
              "Clear Prefetch", "Deletes app preload cache",
              @"del /q /f /s C:\Windows\Prefetch\* 2>nul", @"echo N/A"),
            T("dns_flush", "Сбросить DNS-кэш", "Очищает кэш DNS",
              "Flush DNS Cache", "Clears DNS cache",
              @"ipconfig /flushdns", @"echo N/A"),
            T("recycle", "Очистить корзину", "Удаляет все файлы из корзины",
              "Empty Recycle Bin", "Deletes all recycle bin files",
              @"PowerShell -Command ""Clear-RecycleBin -Force -EA SilentlyContinue""", @"echo N/A"),
            T("event_logs", "Очистить журналы событий", "Стирает все системные логи",
              "Clear Event Logs", "Wipes all event logs",
              @"PowerShell -Command ""wevtutil el | ForEach-Object { wevtutil cl $_ }""", @"echo N/A"),
            T("thumb", "Очистить кэш миниатюр", "Удаляет кэш превью Проводника",
              "Clear Thumbnail Cache", "Deletes Explorer preview cache",
              @"del /f /s /q %LocalAppData%\Microsoft\Windows\Explorer\thumbcache_*.db 2>nul", @"echo N/A"),
            T("upd_cache", "Очистить кэш обновлений", "Освобождает место от загруженных обновлений",
              "Clear Update Cache", "Frees space from update packages",
              @"net stop wuauserv 2>nul & rd /s /q C:\Windows\SoftwareDistribution\Download 2>nul & net start wuauserv 2>nul", @"echo N/A"),
            T("browser_cache", "Очистить кэш браузеров", "Удаляет кэш Chrome и Edge (освобождает место)",
              "Clear Browser Cache", "Deletes Chrome and Edge cache (frees space)",
              @"rd /s /q ""%LocalAppData%\Google\Chrome\User Data\Default\Cache"" 2>nul & rd /s /q ""%LocalAppData%\Microsoft\Edge\User Data\Default\Cache"" 2>nul", @"echo N/A"),
            T("font_cache", "Очистить кэш шрифтов", "Перестраивает повреждённый кэш шрифтов — исправляет проблемы отображения",
              "Clear Font Cache", "Rebuilds the font cache — fixes rendering glitches",
              @"net stop FontCache 2>nul & del /q /f /s ""%LocalAppData%\FontCache\*"" 2>nul & del /q /f ""%WinDir%\ServiceProfiles\LocalService\AppData\Local\FontCache\*"" 2>nul & net start FontCache 2>nul", @"echo N/A"),
            T("icon_cache", "Очистить кэш значков", "Удаляет повреждённый кэш иконок Проводника",
              "Clear Icon Cache", "Deletes the corrupted Explorer icon cache",
              @"del /q /f ""%LocalAppData%\IconCache.db"" 2>nul & del /q /f ""%LocalAppData%\Microsoft\Windows\Explorer\iconcache_*.db"" 2>nul", @"echo N/A"),
            T("crash_dumps", "Очистить дампы памяти (crash)", "Удаляет файлы аварийных дампов — освобождает место",
              "Clear Crash Dumps", "Deletes crash dump files — frees disk space",
              @"del /q /f ""%LocalAppData%\CrashDumps\*"" 2>nul & del /q /f ""%WinDir%\Minidump\*"" 2>nul & del /q /f ""%WinDir%\MEMORY.DMP"" 2>nul", @"echo N/A"),
            T("delivery_opt", "Очистить кэш доставки обновлений", "Удаляет файлы Delivery Optimization, накопленные при раздаче обновлений",
              "Clear Delivery Optimization Cache", "Deletes Delivery Optimization files left from update sharing",
              @"PowerShell -Command ""Delete-DeliveryOptimizationCache -Force -EA SilentlyContinue""", @"echo N/A"),
        };

        data["network"] = new()
        {
            T("tcp_auto", "TCP автотюнинг", "Авто-оптимизация TCP буфера — быстрее скачивание",
              "TCP Autotuning", "Auto TCP buffer optimization",
              @"netsh int tcp set global autotuninglevel=normal",
              @"netsh int tcp set global autotuninglevel=disabled"),
            T("tcp_fast", "TCP Fast Open", "Ускоряет установку соединений",
              "TCP Fast Open", "Faster connection setup",
              @"netsh int tcp set global fastopen=enabled",
              @"netsh int tcp set global fastopen=disabled"),
            T("dns_goog", "DNS Google (8.8.8.8)", "Google DNS для всех адаптеров — быстрее резолв",
              "Google DNS", "Google DNS for all adapters",
              @"PowerShell -Command ""Get-NetAdapter | Where Status -eq Up | Set-DnsClientServerAddress -ServerAddresses ('8.8.8.8','8.8.4.4')""",
              @"PowerShell -Command ""Get-NetAdapter | Where Status -eq Up | Set-DnsClientServerAddress -ResetServerAddresses"""),
            T("dns_cloudflare", "DNS Cloudflare (1.1.1.1)", "Быстрый и приватный DNS Cloudflare для всех адаптеров",
              "Cloudflare DNS (1.1.1.1)", "Fast & private Cloudflare DNS for all adapters",
              @"PowerShell -Command ""Get-NetAdapter | Where Status -eq Up | Set-DnsClientServerAddress -ServerAddresses ('1.1.1.1','1.0.0.1')""",
              @"PowerShell -Command ""Get-NetAdapter | Where Status -eq Up | Set-DnsClientServerAddress -ResetServerAddresses"""),
            T("dns_adguard", "DNS AdGuard (блокировка рекламы)", "DNS AdGuard блокирует рекламу и трекеры на уровне сети",
              "AdGuard DNS (blocks ads)", "AdGuard DNS blocks ads & trackers network-wide",
              @"PowerShell -Command ""Get-NetAdapter | Where Status -eq Up | Set-DnsClientServerAddress -ServerAddresses ('94.140.14.14','94.140.15.15')""",
              @"PowerShell -Command ""Get-NetAdapter | Where Status -eq Up | Set-DnsClientServerAddress -ResetServerAddresses"""),
            T("ipv6_off", "Отключить IPv6", "Упрощает стек сети",
              "Disable IPv6", "Simplifies network stack",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters"" /v DisabledComponents /t REG_DWORD /d 255 /f",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters"" /v DisabledComponents /t REG_DWORD /d 0 /f"),
            T("bw_limit", "Снять лимит полосы (обновления)", "Убирает резервирование 20% канала под обновления",
              "Remove BW Limit", "Remove 20% bandwidth reservation",
              @"reg add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\Psched"" /v NonBestEffortLimit /t REG_DWORD /d 0 /f",
              @"reg delete ""HKLM\SOFTWARE\Policies\Microsoft\Windows\Psched"" /v NonBestEffortLimit /f"),
            T("nagle", "Отключить алгоритм Нагла", "Снижает latency в онлайн-играх",
              "Disable Nagle Algorithm", "Less latency in online games",
              @"reg add ""HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters"" /v TCPNoDelay /t REG_DWORD /d 1 /f",
              @"reg delete ""HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters"" /v TCPNoDelay /f"),
            T("dns_quad9", "DNS Quad9 (9.9.9.9, безопасный)", "Безопасный DNS Quad9 блокирует вредоносные домены для всех адаптеров",
              "Quad9 DNS (9.9.9.9, secure)", "Secure Quad9 DNS blocks malicious domains for all adapters",
              @"PowerShell -Command ""Get-NetAdapter | Where Status -eq Up | Set-DnsClientServerAddress -ServerAddresses ('9.9.9.9','149.112.112.112')""",
              @"PowerShell -Command ""Get-NetAdapter | Where Status -eq Up | Set-DnsClientServerAddress -ResetServerAddresses"""),
            T("teredo_off", "Отключить Teredo", "Выключает туннелирование IPv6 Teredo — иногда снижает задержки и решает проблемы NAT",
              "Disable Teredo", "Turns off Teredo IPv6 tunneling — can lower latency and fix NAT issues",
              @"netsh interface teredo set state disabled",
              @"netsh interface teredo set state default"),
            T("conn_per_server", "Больше одновременных подключений", "Увеличивает лимит одновременных подключений к серверу — быстрее загрузка страниц",
              "More Simultaneous Connections", "Raises the per-server connection limit — faster page loads",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings"" /v MaxConnectionsPerServer /t REG_DWORD /d 16 /f & reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings"" /v MaxConnectionsPer1_0Server /t REG_DWORD /d 16 /f",
              @"reg delete ""HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings"" /v MaxConnectionsPerServer /f & reg delete ""HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings"" /v MaxConnectionsPer1_0Server /f"),
        };

        data["privacy"] = new()
        {
            T("priv_mic", "Отключить доступ к микрофону", "Запрет для UWP-приложений",
              "Disable Microphone Access", "Deny mic for UWP apps",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone"" /v Value /t REG_SZ /d Deny /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\microphone"" /v Value /t REG_SZ /d Allow /f"),
            T("priv_cam", "Отключить доступ к камере", "Запрет для UWP-приложений",
              "Disable Camera Access", "Deny webcam for UWP apps",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam"" /v Value /t REG_SZ /d Deny /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\webcam"" /v Value /t REG_SZ /d Allow /f"),
            T("priv_clip", "Отключить синхронизацию буфера обмена", "Содержимое не уходит в облако Microsoft",
              "Disable Clipboard Sync", "Clipboard won't sync to cloud",
              @"reg add ""HKCU\Software\Microsoft\Clipboard"" /v EnableClipboardHistory /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Clipboard"" /v EnableClipboardHistory /t REG_DWORD /d 1 /f"),
            T("priv_apps", "Отключить отслеживание запуска", "Windows не ведёт статистику запускаемых приложений",
              "Disable App Launch Tracking", "Won't track app launches",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v Start_TrackProgs /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v Start_TrackProgs /t REG_DWORD /d 1 /f"),
            T("show_ext", "Показывать расширения файлов", "Файлы покажут .exe .py .txt",
              "Show File Extensions", "Show .exe .py .txt etc",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v HideFileExt /t REG_DWORD /d 0 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v HideFileExt /t REG_DWORD /d 1 /f"),
            T("show_hide", "Показывать скрытые файлы", "Скрытые и системные файлы видны в Проводнике",
              "Show Hidden Files", "Show hidden/system files",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v Hidden /t REG_DWORD /d 1 /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v Hidden /t REG_DWORD /d 2 /f"),
            T("classic_menu", "Классическое контекстное меню (Win11)", "Возвращает полное меню по правому клику без «Показать доп. параметры»",
              "Classic context menu (Win11)", "Restores the full right-click menu (no 'Show more options')",
              @"reg add ""HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32"" /f /ve",
              @"reg delete ""HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}"" /f"),
            T("god_mode", "Создать ярлык God Mode", "Папка со ВСЕМИ настройками Windows на рабочем столе",
              "Create God Mode shortcut", "A folder with ALL Windows settings on the desktop",
              @"cmd /c mkdir ""%UserProfile%\Desktop\GodMode.{ED7BA470-8E54-465E-825C-99712043E01C}""",
              @"cmd /c rmdir ""%UserProfile%\Desktop\GodMode.{ED7BA470-8E54-465E-825C-99712043E01C}"""),
            T("priv_account_info", "Запретить доступ к данным аккаунта", "UWP-приложения не получают имя, фото и другую информацию учётной записи",
              "Disable Account Info Access", "UWP apps can't read your name, picture or other account info",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userAccountInformation"" /v Value /t REG_SZ /d Deny /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userAccountInformation"" /v Value /t REG_SZ /d Allow /f"),
            T("priv_contacts", "Запретить доступ к контактам", "Запрет для UWP-приложений читать ваши контакты",
              "Disable Contacts Access", "Deny UWP apps access to your contacts",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\contacts"" /v Value /t REG_SZ /d Deny /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\contacts"" /v Value /t REG_SZ /d Allow /f"),
            T("priv_notifications", "Запретить доступ к уведомлениям", "UWP-приложения не могут читать ваши уведомления",
              "Disable Notification Access", "UWP apps can't read your notifications",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userNotificationListener"" /v Value /t REG_SZ /d Deny /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\userNotificationListener"" /v Value /t REG_SZ /d Allow /f"),
            T("priv_diagnostics", "Запретить доступ к диагностике приложений", "UWP-приложения не получают диагностические данные о других программах",
              "Disable App Diagnostics Access", "UWP apps can't read diagnostic info about other programs",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\appDiagnostics"" /v Value /t REG_SZ /d Deny /f",
              @"reg add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\appDiagnostics"" /v Value /t REG_SZ /d Allow /f"),
        };

        return data;
    }
}
